AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Serverless Calculator Application

Resources:

  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: calculator-function
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 10
      MemorySize: 128

      Events:

        AddApi:
          Type: Api
          Properties:
            Path: /add
            Method: post

        SubtractApi:
          Type: Api
          Properties:
            Path: /subtract
            Method: post

        MultiplyApi:
          Type: Api
          Properties:
            Path: /multiply
            Method: post
